version: 0.0
os: linux  # This includes Ubuntu
files:
  - source: /
    destination: /root/assignment1

hooks:
  AfterInstall:
    - location: start_server.sh
      timeout: 300
      runas: root
