version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Or the Node.js version you're using
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo "No build step needed" # This can be changed based on your app needs
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
