version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Adjust this if you're using a different version
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build || echo "No build step required"
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
